// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SuperHero.Infrastructure.Persistence;

#nullable disable

namespace SuperHero.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251211152610_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SuperHero.Domain.Entities.Toy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateOnly?>("FirstAppearance")
                        .HasColumnType("date");

                    b.Property<string>("MainPower")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PowerLevel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Toys");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Alias = "Spider-Man",
                            FirstAppearance = new DateOnly(1962, 8, 1),
                            MainPower = "Spider-sense and agility",
                            Name = "Peter Parker",
                            PowerLevel = 85
                        },
                        new
                        {
                            Id = 2,
                            Alias = "Captain Marvel",
                            FirstAppearance = new DateOnly(1968, 3, 1),
                            MainPower = "Cosmic energy projection",
                            Name = "Carol Danvers",
                            PowerLevel = 95
                        },
                        new
                        {
                            Id = 3,
                            Alias = "Iron Man",
                            FirstAppearance = new DateOnly(1963, 3, 1),
                            MainPower = "Powered armor suit and genius intellect",
                            Name = "Tony Stark",
                            PowerLevel = 90
                        },
                        new
                        {
                            Id = 4,
                            Alias = "Captain America",
                            FirstAppearance = new DateOnly(1941, 3, 1),
                            MainPower = "Enhanced strength and tactical leadership",
                            Name = "Steve Rogers",
                            PowerLevel = 88
                        },
                        new
                        {
                            Id = 5,
                            Alias = "Black Widow",
                            FirstAppearance = new DateOnly(1964, 4, 1),
                            MainPower = "Elite spy, martial arts and espionage",
                            Name = "Natasha Romanoff",
                            PowerLevel = 78
                        },
                        new
                        {
                            Id = 6,
                            Alias = "Thor",
                            FirstAppearance = new DateOnly(1962, 8, 1),
                            MainPower = "God of thunder and Mjolnir",
                            Name = "Thor Odinson",
                            PowerLevel = 97
                        },
                        new
                        {
                            Id = 7,
                            Alias = "Hulk",
                            FirstAppearance = new DateOnly(1962, 5, 1),
                            MainPower = "Limitless rage-fueled strength",
                            Name = "Bruce Banner",
                            PowerLevel = 96
                        },
                        new
                        {
                            Id = 8,
                            Alias = "Black Panther",
                            FirstAppearance = new DateOnly(1966, 7, 1),
                            MainPower = "Enhanced abilities and vibranium suit",
                            Name = "T'Challa",
                            PowerLevel = 89
                        },
                        new
                        {
                            Id = 9,
                            Alias = "Doctor Strange",
                            FirstAppearance = new DateOnly(1963, 7, 1),
                            MainPower = "Master of the mystic arts",
                            Name = "Stephen Strange",
                            PowerLevel = 93
                        },
                        new
                        {
                            Id = 10,
                            Alias = "Scarlet Witch",
                            FirstAppearance = new DateOnly(1964, 3, 1),
                            MainPower = "Reality-warping chaos magic",
                            Name = "Wanda Maximoff",
                            PowerLevel = 98
                        },
                        new
                        {
                            Id = 11,
                            Alias = "Ant-Man",
                            FirstAppearance = new DateOnly(1979, 9, 1),
                            MainPower = "Size manipulation and tech expertise",
                            Name = "Scott Lang",
                            PowerLevel = 80
                        },
                        new
                        {
                            Id = 12,
                            Alias = "Wolverine",
                            FirstAppearance = new DateOnly(1974, 10, 1),
                            MainPower = "Regeneration and adamantium claws",
                            Name = "Logan",
                            PowerLevel = 92
                        },
                        new
                        {
                            Id = 13,
                            Alias = "Wonder Woman",
                            FirstAppearance = new DateOnly(1941, 12, 1),
                            MainPower = "Amazonian strength and lasso of truth",
                            Name = "Diana Prince",
                            PowerLevel = 96
                        },
                        new
                        {
                            Id = 14,
                            Alias = "The Flash",
                            FirstAppearance = new DateOnly(1956, 10, 1),
                            MainPower = "Super speed and Speed Force",
                            Name = "Barry Allen",
                            PowerLevel = 94
                        },
                        new
                        {
                            Id = 15,
                            Alias = "Aquaman",
                            FirstAppearance = new DateOnly(1941, 11, 1),
                            MainPower = "Atlantean strength and control over the seas",
                            Name = "Arthur Curry",
                            PowerLevel = 88
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
