// <auto-generated/>
using SuperHero.UI.Models;

namespace SuperHero.UI.Pages.Superheroes
{
    public partial class Superheroes
    {
        private List<SuperHeroViewModel> heroes = new();
        private SuperHeroEditModel editModel = new() { PowerLevel = 50 };

        private bool isLoading;
        private bool isEditMode;
        private int? selectedHeroId;
        private string? errorMessage;
        private string searchTerm = string.Empty;

        private List<SuperHeroViewModel> FilteredHeroes =>
            string.IsNullOrWhiteSpace(searchTerm)
                ? heroes
                : heroes
                    .Where(h =>
                        (!string.IsNullOrWhiteSpace(h.Alias) &&
                         h.Alias.Contains(searchTerm, StringComparison.OrdinalIgnoreCase)) ||
                        (!string.IsNullOrWhiteSpace(h.Name) &&
                         h.Name.Contains(searchTerm, StringComparison.OrdinalIgnoreCase)))
                    .ToList();

        protected override async Task OnInitializedAsync()
        {
            await LoadHeroesAsync();
        }

        private async Task LoadHeroesAsync()
        {
            isLoading = true;
            errorMessage = null;

            try
            {
                heroes = await ApiClient.GetAllAsync();
            }
            catch (Exception ex)
            {
                errorMessage = $"Could not load heroes: {ex.Message}";
            }
            finally
            {
                isLoading = false;
            }
        }

        private void EditHero(SuperHeroViewModel hero)
        {
            isEditMode = true;
            selectedHeroId = hero.Id;

            editModel = new SuperHeroEditModel
            {
                Name = hero.Name,
                Alias = hero.Alias,
                MainPower = hero.MainPower,
                PowerLevel = hero.PowerLevel,
                FirstAppearance = hero.FirstAppearance
            };
        }

        private async Task SaveAsync()
        {
            try
            {
                if (isEditMode && selectedHeroId.HasValue)
                {
                    await ApiClient.UpdateAsync(selectedHeroId.Value, editModel);
                }
                else
                {
                    await ApiClient.CreateAsync(editModel);
                }

                ResetForm();
                await LoadHeroesAsync();
            }
            catch (Exception ex)
            {
                errorMessage = $"Could not save hero: {ex.Message}";
            }
        }

        private async Task DeleteHeroAsync(int id)
        {
            try
            {
                await ApiClient.DeleteAsync(id);

                if (selectedHeroId == id)
                {
                    ResetForm();
                }

                await LoadHeroesAsync();
            }
            catch (Exception ex)
            {
                errorMessage = $"Could not delete hero: {ex.Message}";
            }
        }

        private void ResetForm()
        {
            isEditMode = false;
            selectedHeroId = null;
            editModel = new SuperHeroEditModel
            {
                PowerLevel = 50
            };
        }
    }
}